### ISSUE TITLE
Update documentation and provide api examples

### ISSUE THREAD

**Issue by stern0** [slipstream/SlipStreamPythonAPI#46]
The Api internally inside the library is documented but there's no proper documentation and on the github Readme or on the SlipStream API Reference.

Actually the documentation on github is wrong, an example is the following official README on github:
```python
from slipstream.api import Api
api = Api('https://nuv.la')
api.login('username', 'password')
api.list_applications()
```
The above raises an error at runtime with:
```
Traceback (most recent call last):
  File "SlipStreamdeploysample.py", line 10, in <module>
    api.login('username', 'password')
TypeError: login() takes exactly 2 arguments (3 given)
```

I then went through the Python Api library which is:

```python
def login(self, login_params):
```
With the `login_params` parameter being a dictionary.

But inside the same class there is the following function: 
```python
def login_internal(self, username, password):
```
and it utilises `def login(self, login_param):` and has username and password parameters as strings.

Which shows the README docs is a wrong and need fixing or must be updated if so.

Another issue I wanted to mention is the lack of examples with the package. As a user, having clear and practical examples helps understanding the Api and makes you understand the docs better in most cases.

An example could be the following:

```python
from slipstream.api import Api
api = Api('https://nuv.la')
api.login_internal('username', 'password')

# To deploy and get deployment ID
deployment_id = api.deploy('app/mysql/v1', cloud='ec2-us-west-2')

# To terminate
api.terminate(deployment_id)

# To logout
api.logout()
```

The above is a simple basic deployment example but there's no similar example provided in the docs, on the other hand more complex examples are needed since all production deployments are a lot more complex than the above.

**Comment by schaubl** [comment]
@cryst10 Thanks for your feedback.

I updated the README.

You can find an HTML version of the documentation here: 
https://slipstream.github.io/SlipStreamPythonAPI

**Comment by cryst10** [comment]
@schaubl Thanks for updates

The example on the README that which I gave is this issue was a very basic example to play around with the library.

I thought if there could be complex examples or usage of the library, since there's none.
The internal docs and HTML versions are good but not example usage for a user.

For example this library uses the well known **requests** library in the python community, and although it has no docs the github README, has a lot of real user examples and an extensive documentation on the website, which makes it easy to use, although bigger as a library.
